const styles = {
  container: {
    display: 'flex',
    height: '100vh',
    background: 'linear-gradient(to bottom, #e0f2fe, #dcfce7)',
  },
  sidebar: {
    width: '16rem',
    backgroundColor: 'white',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    padding: '1rem',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  sidebarTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: '#15803d',
    marginBottom: '1rem',
  },
  buttonGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    marginBottom: '1rem',
  },
  button: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1rem',
    borderRadius: '0.5rem',
    transition: 'all 0.2s',
    fontWeight: '600',
    border: 'none',
    cursor: 'pointer',
  },
  buttonSun: {
    backgroundColor: '#fbbf24',
    color: 'white',
  },
  buttonWater: {
    backgroundColor: '#60a5fa',
    color: 'white',
  },
  buttonGrass: {
    backgroundColor: '#22c55e',
    color: 'white',
  },
  buttonDisabled: {
    backgroundColor: '#d1d5db',
    color: '#6b7280',
    cursor: 'not-allowed',
  },
  toggleButtons: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  toggleButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.5rem 0.75rem',
    borderRadius: '0.5rem',
    transition: 'all 0.2s',
    fontWeight: '600',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  panelContent: {
    flex: 1,
    overflowY: 'auto',
  },
  inventoryPanel: {
    padding: '0.75rem',
    backgroundColor: '#faf5ff',
    borderRadius: '0.5rem',
    border: '2px solid #e9d5ff',
  },
  inventoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '0.5rem',
  },
  inventoryItem: {
    cursor: 'move',
    transition: 'transform 0.2s',
    backgroundColor: 'white',
    padding: '0.5rem',
    borderRadius: '0.5rem',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    position: 'relative',
    aspectRatio: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logsPanel: {
    backgroundColor: '#f0fdf4',
    borderRadius: '0.5rem',
    padding: '0.75rem',
    border: '2px solid #bbf7d0',
  },
  logEntry: {
    color: '#374151',
    padding: '0.25rem 0.5rem',
    borderBottom: '1px solid #bbf7d0',
    fontSize: '0.75rem',
  },
  mainContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
  },
  currency: {
    position: 'absolute',
    top: '1rem',
    left: '1rem',
    backgroundColor: '#fde047',
    padding: '0.5rem 1rem',
    borderRadius: '9999px',
    fontWeight: 'bold',
    fontSize: '1.125rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    zIndex: 10,
  },
  gachaButton: {
    position: 'absolute',
    top: '1rem',
    right: '1rem',
    width: '6rem',
    height: '6rem',
    borderRadius: '9999px',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    transition: 'all 0.3s',
    zIndex: 10,
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  playArea: {
    flex: 1,
    background: 'linear-gradient(to bottom, #bae6fd, #bbf7d0)',
    position: 'relative',
    overflow: 'hidden',
  },
  draggable: {
    position: 'absolute',
    cursor: 'move',
    transition: 'transform 0.2s',
  },
  statsBar: {
    backgroundColor: 'white',
    borderTop: '4px solid #22c55e',
    padding: '1rem',
    boxShadow: '0 -4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1.5rem',
    maxWidth: '48rem',
    margin: '0 auto',
  },
  statItem: {
    textAlign: 'center',
  },
  statLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    marginBottom: '0.5rem',
  },
  statBar: {
    width: '100%',
    backgroundColor: '#e5e7eb',
    borderRadius: '9999px',
    height: '1.5rem',
    overflow: 'hidden',
    border: '2px solid #d1d5db',
  },
  modal: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 50,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: '0.5rem',
    padding: '1.5rem',
    maxWidth: '28rem',
    width: '90%',
    margin: '0 1rem',
  },
};